const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const cursor=$('.cursor');window.addEventListener('pointermove',e=>{if(cursor){cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'}});
$$('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.12}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
const menu=$('.menu-btn'),mobile=$('.mobile-nav');menu?.addEventListener('click',()=>mobile.classList.toggle('open'));$$('.mobile-nav a').forEach(a=>a.addEventListener('click',()=>mobile.classList.remove('open')));
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(x=>observer.observe(x));
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1800)}
$$('.service-pill').forEach(x=>x.addEventListener('click',()=>{$$('.service-pill').forEach(y=>y.classList.remove('active'));x.classList.add('active');toast(x.dataset.service+' selected')}));
$$('[data-reel]').forEach(x=>x.addEventListener('click',()=>toast('Reel preview coming next — thanks for stopping by.')));
const art=$('.hero-art');art?.addEventListener('pointermove',e=>{const r=art.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;art.style.transform=`rotateY(${x*3}deg) rotateX(${y*-3}deg)`});art?.addEventListener('pointerleave',()=>art.style.transform='');
const countObs=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,end=+el.dataset.count,start=performance.now(),suffix=el.textContent.includes('%')?'%':'+';function tick(t){const p=Math.min((t-start)/1000,1);el.textContent=Math.round(end*(1-Math.pow(1-p,3)))+suffix;if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick);countObs.unobserve(el)}),{threshold:.6});$$('[data-count]').forEach(x=>countObs.observe(x));
const cards=$$('.work-card');const shift=dir=>{cards.forEach((c,i)=>c.style.transform=`translateX(${i?dir*14:0}px)`);setTimeout(()=>cards.forEach(c=>c.style.transform=''),420)};$('.work-arrow[data-next]')?.addEventListener('click',()=>shift(-1));$('.work-arrow[data-prev]')?.addEventListener('click',()=>shift(1));
$$('[data-toast]').forEach(x=>x.addEventListener('click',()=>toast(x.dataset.toast)));
$('#briefForm')?.addEventListener('submit',e=>{e.preventDefault();const m=$('.form-message');m.textContent='Brief received — we’ll get back to you shortly.';e.target.reset();toast('Brief sent successfully')});
$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(id==='#contact'||id==='#insights'){e.preventDefault();toast(id==='#contact'?'Project enquiry opened — tell us what you need.':'Insights section is being prepared.');return}if(id&&id.length>1){const el=$(id);if(el){e.preventDefault();el.scrollIntoView({behavior:'smooth'})}}}));
